import type { NextPage } from 'next';
import Head from 'next/head';
import {
  getPokemon,
  getPokemonGeneration,
  getPokemonInterval,
} from './api/endpoints';

import { SiPokemon } from 'react-icons/si';
import { SiGithub } from 'react-icons/si';
import { Container, Footer, Header, Main } from './styles';
import { useEffect, useState } from 'react';

interface pokemon {
  name: string;
  url: string;
}

const Home: NextPage = () => {
  const [listPokemon, setListPokemon] = useState([]);
  const [onePokemon, setOnePokemon] = useState({});
  const [openPokemon, setOpenPokemon] = useState(false);

  useEffect(() => {
    getPokemonInterval(0, 151, setListPokemon);
  }, []);

  return (
    <Container>
      <Head>
        <title>Pokedéx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <SiPokemon />
      </Header>

      <Main>
        {!openPokemon &&
          listPokemon?.map((value: pokemon) => (
            <div className="cardPokemon" key={value?.name}>
              <button
                onClick={() => {
                  getPokemon(value?.name, setOnePokemon);
                  setOpenPokemon(!openPokemon);
                }}
              >
                {value?.name}
              </button>
            </div>
          ))}

        {openPokemon && (
          <div>
            <div>{onePokemon?.name}</div>
            <button
              onClick={() => {
                setOpenPokemon(!openPokemon);
              }}
            >
              voltar
            </button>
          </div>
        )}
      </Main>

      <Footer>
        <a
          href="https://github.com/felipebmuniz"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>
            Powered by Felipe B. Muniz <SiGithub />
          </p>
        </a>
      </Footer>
    </Container>
  );
};

export default Home;
