import type { NextPage } from 'next';
import Head from 'next/head';
import { getPokemon, getPokemonGeneration } from './api/endpoints';

import { SiPokemon } from 'react-icons/si';
import { SiGithub } from 'react-icons/si';
// import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pokedéx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <SiPokemon size={200} />
      </header>

      <main>
        <button
          onClick={() => {
            getPokemonGeneration('');
            getPokemon('charmander');
          }}
        >
          click
        </button>
      </main>

      <footer>
        <a
          href="https://github.com/felipebmuniz"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>
            Powered by Felipe B. Muniz <SiGithub />
          </p>
        </a>
      </footer>
    </div>
  );
};

export default Home;
